export interface Contract {
    idPlayer: number,
    idTeam: number,
    idContract: number,
    firstName: string,
    lastName: string,
    position: string,
    birth_date: Date,
    playerImage: string,
    name: string,
    country: string,
    fundation: string,
    teamImage: string,
    games: number,
    goals: number,
    assits: number,
    salary: string,
    beginDate: Date,
    endDate: Date,
    createdDate: Date,
    modifiedDate: Date
}

export interface PlayerbyContract {
    idPlayer: number,
    idTeam: number,
    firstName: string,
    lastName: string,
    position: string,
    birth_date: Date,
    cost: string,
    playerImage: string,
    name: string,
    country: string,
    fundation: string,
    teamImage: string,
    games: number,
    goals: number,
    assits: number,
    salary: string,
    beginDate: Date,
    endDate: Date,
    createdDate: Date,
    modifiedDate: Date
}